project:
  type: default

format:
  html:
    css: styles/house-style.css
    toc: true
    number-sections: true
  pdf:
    include-in-header: ../../.house-style/preamble.tex
    number-sections: true
